#Linear Regression from Scratch options

In [1]:
import numpy as np

#X and y values

In [2]:
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

#Option 1:

Compute the (multiplicative) inverse of a matrix.

In [4]:
X_b = np.c_[np.ones((100, 1)), X] # add x0 = 1 to each instance
opt_theta = np.linalg.inv((X_b.T@X_b))@X_b.T@y
opt_theta

array([[3.9157229 ],
       [3.20856981]])

#Option 2:

Return the least-squares solution to a linear matrix equation.

In [5]:
theta_best_svd, residuals, rank, s = np.linalg.lstsq(X_b, y, rcond=1e-6)
theta_best_svd

array([[3.9157229 ],
       [3.20856981]])

#Option 3 (SVD):

Compute the (Moore-Penrose) pseudo-inverse of a matrix.

Calculate the generalized inverse of a matrix using its singular-value decomposition (SVD) and including all large singular values.

In [6]:
np.linalg.pinv(X_b)@y

array([[3.9157229 ],
       [3.20856981]])

#Option 4 (Gradient Descent):

In [8]:
alpha = 0.1 # learning rate
n_iterations = 1000
m=100
theta = np.random.randn(2,1) # random initialization
for iteration in range(n_iterations):
	gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
	theta = theta - alpha * gradients
theta

array([[3.9157229 ],
       [3.20856981]])